defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
# submitit_folder: ${hydra.sweep.dir}/.submitit/%j
# name: ${hydra.job.name} # name of the job
timeout_min: 60 # maximum time for the job in minutes
cpus_per_task: null # number of cpus to use for each task
gpus_per_node: null # number of gpus to use on each node
tasks_per_node: 1 # number of tasks to spawn on each node
mem_gb: null # memory to reserve for the job on each node (in GB)
# stderr_to_stdout: false # redirect stderr to stdout
nodes: 1 # number of nodes to use for the job
partition: ${calculate_partition_type:${hydra.launcher.timeout_min}}
qos: null
comment: null
constraint: null
exclude: null
gres: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
account: null
signal_delay_s: 120 # USR1 signal delay before timeout
max_num_timeout: 0 #  Maximum number of retries on job timeout. Change this only after you confirmed your code can handle re-submission by properly resuming from the latest stored checkpoint.
array_parallelism: 256 # Maximum number of jobs running in parallel
additional_parameters: {} # Useful to add parameters which are not currently available in the plugin. Eg: {"mail-user": "blublu@fb.com", "mail-type": "BEGIN"}
setup: null # Optional[List[str]] A list of commands to run in sbatch befure running srun
# srun_args: null # Optional[List[str]] Any additional arguments that should be passed to srun
