train:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  persistent_workers: True
  pin_memory: False
val:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  persistent_workers: True
  pin_memory: False
test:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  persistent_workers: True
  pin_memory: False
