_target_: model.models.combined_model_v2.CombinedModel
context_norm: true

in_dim: 1024

relational_module_real:
  _target_: model.models.relational_module.RelationalModule
  object_size: 1024
  asymetrical: true
  rel_activation_func: 'softmax'
  context_norm: true
  hierarchical: false
  ckpt_path: null
  freeze_module: false
  loading_name: 'relational_module_real'


relational_module_abstract:
  _target_: model.models.relational_module.RelationalModule
  object_size: 1024
  asymetrical: true
  rel_activation_func: 'softmax'
  context_norm: true
  hierarchical: false
  ckpt_path: null
  freeze_module: false
  loading_name: 'relational_module_abstract'

relational_scoring_module:
  _target_: model.models.relational_module.RelationalScoringModule
  in_dim: 80
  hidden_dim: [128]
  pooling: 'max'
  transformer: null
  ckpt_path: null
  freeze_module: false
  layers_to_train: [1]


save_hyperparameters: true

limit_to_groups: false

slot_model:
  _target_: model.models.STSNv3.SlotAttentionAutoEncoder
  resolution:
    - ${img_size}
    - ${img_size}
  num_slots: 20
  hid_dim: 64
  num_iterations: 3
  ckpt_path: null
  save_hyperparameters: false
  save_slots: false
  freeze_slot_model: true

