_target_: model.models.combined_model_v3.CombinedModel
context_norm: true

in_dim: 1024

relational_module:
  _target_: model.models.relational_module.RelationalModule
  object_size: 1024
  asymetrical: true
  rel_activation_func: 'softmax'
  context_norm: true
  hierarchical: false
  ckpt_path: null
  freeze_module: false


relational_scoring_module_1:
  _target_: model.models.relational_module.RelationalScoringModule
  in_dim: 80
  hidden_dim: 128
  pooling: 'max'
  transformer: null
  ckpt_path: null
  freeze_module: false
  layers_to_train: [1]


relational_scoring_module_2:
  _target_: model.models.relational_module.RelationalScoringModule
  in_dim: 80
  hidden_dim: 128
  pooling: 'max'
  transformer: null
  ckpt_path: null
  freeze_module: false
  layers_to_train: [1]

real_idxes: [0]
use_separate_aggregators: false
save_hyperparameters: true

limit_to_groups: false

slot_model: null
